name: CPP Pr example
on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build code
        run: |
          mkdir build
          cd build 
          cmake ..
          make

      - name: pwd
        run: pwd && ls -la

      - name: compress_exetutable
        run: tar -cvf MyProject.tar ./build/MyProject 


      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: MyProject.tar
          path: MyProject.tar

  dynamic-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Valgrind
        run: sudo apt-get install valgrind

      - name: Download executable
        uses: actions/download-artifact@v3
        with:
          name: MyProject.tar
          path: MyProject.tar

      - name: Check folder
        run: ls -la ./MyProject.tar

      - name: Tar exetutable
        run: tar -xvzf MyProject.tar/MyProject.tar

      - name: Check folder
        run: ls -la ./

      - name: Run Valgrind
        run: valgrind --leak-check=full ./build/MyProject
      - name: Upload Valgrind results
        uses: actions/upload-artifact@v3
        with:
          name: valgrind-results
          path: valgrind-results.txt

  # static-analysis:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install Cppcheck
  #       run: sudo apt-get install cppcheck

  #     - name: Run Cppcheck
  #       run: cppcheck --enable=all --suppress=missingInclude --include=include .
  #       id: cppcheck

  #     - name: Upload Cppcheck results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cppcheck-results
  #         path: cppcheck-results.xml

  #     - name: Install Cpplint
  #       run: sudo apt-get install python3-pip && pip3 install cpplint

  #     - name: Run Cpplint
  #       run: cpplint --recursive .
  #       id: cpplint

  #     - name: Upload Cpplint results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cpplint-results
  #         path: cpplint-results.txt    
  
    
  
