name: CPP Pr example
on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      uses: actions/checkout@v2
      run: |
        mkdir build
        cd build 
        cmake ..
        make

    
  
