name: CPP Pr example
on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout code
        run: |
          mkdir build
          cd build 
          cmake ..
          make

    
  
