name: CPP Pr example
on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build code
        run: |
          mkdir build
          cd build 
          cmake ..
          make

  cppcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Run Cppcheck
        uses: actions/checkout@v2
        run: cppcheck --language=c++ --enable=all .
        id: cppcheck

      - name: Upload Cppcheck results
        with:
          name: cppcheck-results
          path: cppcheck-results.xml

      - name: Run Cpplint
        uses: actions/checkout@v2
        run: cpplint --recursive .
        id: cpplint

      - name: Upload Cpplint results
        with:
          name: cpplint-results
          path: cpplint-results.txt    
  
    
  
